### ISSUE TITLE
httpdFreertosStart shutdown/deinit

### ISSUE THREAD

**Issue by Elektrik1** [chmorgan/esphttpd-freertos#8]
Hello,

Can't find any documentation how to deinit httpd instance, it causes StoreProhibited error wen trying to esp_wifi_stop(); and esp_wifi_deinit(); after httpdFreertosStart was called, resulting in no possibility to turn off wifi dynamically with httpd server.

**Comment by chmorgan** [comment]
Sorry for the late response.

In include/libesphttpd/httpd.h,
https://github.com/chmorgan/libesphttpd/blob/master/include/libesphttpd/httpd.h

You’ll find httpdShutdown() that you can use to stop the server thread. It
is optional to save code space although I’m not sure that option actually
does as the compiler should exclude it if you don’t call it.

Chris

**Comment by Elektrik1** [comment]
Thank you for your response.

It seems that there is some misalign with FreeRTOS/linux version of shutdown. I do use it on FreeRTOS (ESP32), and calling `httpdShutdown(&httpdFreertosInstance);` causes an error:

> components/libesphttpd/include/libesphttpd/httpd.h:226:6: note: expected 'struct HttpdInstance *' but  argument is of type 'HttpdFreertosInstance * {aka struct < anonymous > *}'
>  void httpdShutdown(HttpdInstance *pInstance);
>       ^

am I missing something ?

Thank you.

**Comment by chmorgan** [comment]
Yep, you want this:

httpdShutdown(&httpdFreertosInstance.httpdInstance);

**Comment by Elektrik1** [comment]
Thank you very much, work like a charm!

Have a nice day
